version: '3.9'
services:
    database:
        image: "postgres:14.1-alpine"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        ports:
            - "5430:5432"
        # volumes:
        #     - db-data:/foo
    webscrapping:
        image: scraper
        build:
            context: webscrapping
            dockerfile: Dockerfile
        environment:
            - PGUSER=postgres
            - PGHOST=database
            - PGPASSWORD=postgres
            - PGDATABASE=postgres
            - PGPORT=5432
        depends_on:
            - database
    app:
        image: scrape-app
        build: server
        environment:
            - PORT=4000
            - PGUSER=postgres
            - PGHOST=database
            - PGPASSWORD=postgres
            - PGDATABASE=postgres
            - PGPORT=5432
        ports:
            - "8080:4000"
        restart: on-failure
        depends_on:
            - database
# volumes:
#     db-data:

