version: '3.9'
services:
    database:
        image: "postgres:14.1-alpine"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        ports:
            - "5430:5432"
        volumes:
            - db-data:/foo
    webscrapping:
        image: scraper
        build:
            context: webscrapping
            dockerfile: Dockerfile
    # app:
    #     image: scrape-app
    #     build: server
    #     ports:
    #         - "8080:4000"
    #     depends_on:
    #         - database
volumes:
    db-data:

